### ISSUE TITLE
Namespaced controllers and lazy lookup

### ISSUE THREAD

**Issue by gzigzigzeo** [lotus/router#44]
I have Admin namespace for actions in my application.

```ruby
namespace 'admin' do
  get 'coupons', to: 'admin/coupons#index'
end
```

expected to open `Web::Controllers::Admin::Coupons::Index` but fails with `Lotus::Routing::EndpointNotFound: wrong constant name Admin/coupons`.

`Rack::Utils::String#constantize` does not support namespaces like ActiveSupport do. Would it be right way to implement namespacing support in Rack::Utils?

**Comment by jodosha** [comment]
@gzigzigzeo Yes, I think that it can be addressed in Utils. Would you love to take care of it? Thank you.

**Comment by gzigzigzeo** [comment]
@jodosha sure, i'll take it.

**Comment by gzigzigzeo** [comment]
@jodosha Close it please

**Comment by jodosha** [comment]
Resolved by https://github.com/lotus/utils/pull/65
