### ISSUE TITLE
Domain based routing

### ISSUE THREAD

**Issue by cgarvis** [lotus/router#48]
How would lotus router handle routing based on domains and/or subdomains?

**Comment by joneslee85** [comment]
@cgarvis can you please give one example?

**Comment by cgarvis** [comment]
Basically something like [rack-subdomain](https://github.com/mattt/rack-subdomain)

**Comment by AlfonsoUceda** [comment]
@cgarvis do you tell handle routes like 'api.my_host.com' or 'admin.my_host.com' ???

**Comment by AlfonsoUceda** [comment]
ping @cgarvis

**Comment by joneslee85** [comment]
ping @cgarvis

**Comment by cgarvis** [comment]
Yes.  Basic I want to be able to mount different apps on different domains/subdomains.

**Comment by jodosha** [comment]
I'm gonna close this, we can consider this feature for the future.
