### ISSUE TITLE
path and url for mounted application don't include mount point

### ISSUE THREAD

**Issue by danelowe** [lotus/router#53]
Please point me in the right direction if I am doing this wrong. 

To reproduce, I created a new lotus application 

`lotus new test`

I changed the mount point for the 'Web' app from '/' to '/test', and added a resource to `app/web/config/routes.rb`

```
➜  test git:(master) ✗ bundle exec lotus routes
                     GET, HEAD  /test/page                     Web::Controllers::Home::Index
                pigs GET, HEAD  /test/pigs                     Web::Controllers::Pigs::Index
            new_pigs GET, HEAD  /test/pigs/new                 Web::Controllers::Pigs::New
                pigs POST       /test/pigs                     Web::Controllers::Pigs::Create
                pigs GET, HEAD  /test/pigs/:id                 Web::Controllers::Pigs::Show
           edit_pigs GET, HEAD  /test/pigs/:id/edit            Web::Controllers::Pigs::Edit
                pigs PATCH      /test/pigs/:id                 Web::Controllers::Pigs::Update
                pigs DELETE     /test/pigs/:id                 Web::Controllers::Pigs::Destroy
```

in `apps/web/templates/home/index.html.erb` I added `<%= Web::Routes.path(:pigs) %>`

Started the server and looked at the page, the path rendered is `/pigs`, but would expect it to be `/test/pigs`

The rake task is aware of the mount point, but within the view context, the apps routes object does not seem to be aware of its own mount point? 

I've spent a lot of time looking into the routing code, and haven't really found anything obvious.

**Comment by joneslee85** [comment]
@danelowe it is a known issue, because routings are not flatten atm. It is on our roadmap. For now, please workaround the issue by create your own routing helper and append the `/test` prefix.
