### ISSUE TITLE
Routes broken after updating to 0.4.0

### ISSUE THREAD

**Issue by darwinrc** [lotus/router#54]
After updating Lotus to 0.3.1 (lotus-router to 0.4.0) I am getting Lotus::Routing::InvalidRouteException: HttpRouter::TooManyParametersException in all my routes

This is the configuration of my current routes:

https://gist.github.com/darwinrc/c7a4457ffe27de573d25

**Comment by AlfonsoUceda** [comment]
@darwinrc can you post a backtrace?

**Comment by darwinrc** [comment]
Here's the trace: https://gist.github.com/darwinrc/c1ee0a291128784a56c5

**Comment by darwinrc** [comment]
And here's my lotus routes: https://gist.github.com/darwinrc/1db5c0ff3c7aca3ec235

**Comment by AlfonsoUceda** [comment]
@darwinrc can you paste this line? `/home/darwin/dev/kommit/mobijob/mobijob-backend/apps/web/views/application_layout.rb:21:in `new_job_path'`

**Comment by darwinrc** [comment]
Web::Routes.path(:jobs, :new)

**Comment by AlfonsoUceda** [comment]
@darwinrc try `Web::Routes.path(:new_job)`, and if you updated lotus gem, you can use routes helpers in view. In your application.rb there is a view.prepare block:
```ruby
view.prepare do
  include Lotus::Helpers
end
```
then this module is injected https://github.com/lotus/helpers/blob/master/lib/lotus/helpers/routing_helper.rb
and you can replace `Web::Routes.path(:new_job)` with `routes.new_job_path`

The same for controllers, but this behaviour is added by default https://github.com/lotus/lotus/commit/1040a996bdab8762aebcbd293b9cb1d2bcdaac65

PD: please update your code with this new syntax

**Comment by darwinrc** [comment]
I made the changes and it worked! I called it with routes.new_job_path. I'm proceeding with the update then.

Thanks a lot, @AlfonsoUceda

**Comment by jodosha** [comment]
@darwinrc I'm closing this. @AlfonsoUceda Thank you :+1:
