### ISSUE TITLE
Strange routes for two mounted apps

### ISSUE THREAD

**Issue by vyper** [lotus/router#65]
I used a container with two apps:
- web
- api

But the routes' behaviour is very strange.

```ruby
# config/environment.rb
Lotus::Container.configure do
  mount Api::Application, at: '/api'
  mount Web::Application, at: '/'
end

# apps/web/config/routes.rb
get    '/', to: 'pets#index',            as: :root

# apps/api/config/routes.rb
resources :pets, only: :index
```

I get this results for `lotus routes` command:
```
pets GET, HEAD  /api/api/pets                  Api::Controllers::Pets::Index
root GET, HEAD  /                              Web::Controllers::Pets::Index
```

To get the expected behaviour I changed my source as follows:

```ruby
# config/environment.rb
Lotus::Container.configure do
  namespace :api do
    mount Api::Application, at: '/'
  end
  mount Web::Application, at: '/'
end

# apps/web/config/routes.rb
get    '/', to: 'pets#index',            as: :root

# apps/api/config/routes.rb
namespace :api do
  resources :pets, only: :index
end
```

Results:

```ruby
api_pets GET, HEAD  /api/pets                      Api::Controllers::Pets::Index
    root GET, HEAD  /                              Web::Controllers::Pets::Index
```

When I consume the `http://localhost:2300/api/pets` endpoint it works:
```bash
curl http://localhost:2300/api/pets
[]
```

But, when I try to reach `http://localhost:2300/` I got a `404 Not found`:
```bash
curl -I http://localhost:2300/
HTTP/1.1 404 Not Found
Content-Type: application/octet-stream
```

I found it quite strange or am I doing some mistake?

**Comment by jodosha** [comment]
@vyper Hello and thanks for reporting this. Which version of `lotus-router` are you using? Does current `master` solves your issue? @AlfonsoUceda did some fixes for route prefixes that are now living in master. Would you mind to try and let us to know? Thank you! :mouse:

**Comment by vyper** [comment]
I was using: lotus-router (0.4.1).
Now, I changed to `master` (0.4.2) and it's worked. (:
