### ISSUE TITLE
Wrong generation of name for named routes.

### ISSUE THREAD

**Issue by theocodes** [lotus/router#69]
Hey all :+1: 

Just picked up this one today..

when doing something like this in the `routes.rb` file:

```ruby
resources :horses
```

will result in this: 

```
hors GET, HEAD  /horses                        Routertest::Controllers::Horses::Index
new_hors GET, HEAD  /horses/new                    Routertest::Controllers::Horses::New
hors POST       /horses                        Routertest::Controllers::Horses::Create
hors GET, HEAD  /horses/:id                    Routertest::Controllers::Horses::Show
edit_hors GET, HEAD  /horses/:id/edit               Routertest::Controllers::Horses::Edit
hors PATCH      /horses/:id                    Routertest::Controllers::Horses::Update
hors DELETE     /horses/:id                    Routertest::Controllers::Horses::Destroy
```

Thinking it was something related to it ending in 'es' (which i'm still not 100% convinced it isn't) i tried other words such as `:moustaches` and `:stones` and they worked fine. Intriguing huh? ;-)

This is on 0.5.0 and has been around for quite sometime as far as I can tell.. I know that `:horses` is not the most common name in the world for a resource and this may very well be a super-duper edge case.. But it shouldn't happen anyways ;-)

I'll try to look into it in the next few days and report back or send PR this way.

Cheers

**Comment by jodosha** [comment]
Hey @theocodes this has been fixed. :wink:

**Comment by jodosha** [comment]
@theocodes FYI - Since Lotus v0.6.0, there will be possible to customize inflections: https://github.com/lotus/utils/pull/90

**Comment by theocodes** [comment]
@jodosha cool! The will come in handy for sure! :)
