### ISSUE TITLE
router#params not merged into action#params on request with validations

### ISSUE THREAD

**Issue by SleeplessByte** [lotus/router#80]
Given a `:patch` request to `/myfoo/:id` with some data
````Ruby
{
   _method: "PATCH",
  foo: { bar: 'foobar' }	
}
````

With `params` validations
````Ruby
params do
  param :foo do
    param: :bar, type: String
  end
end
````

Accessing the `params` in a controller:
````Ruby
params[:foo]  # {bar: 'foobar'}
params[:id]   # nil
````

But `router.params` does report
````Ruby
{:id=>"1"}
````
-------------------

Adding
````
    param :id`
    [...]
```

Solves the problem. I don't think I should explicitly add router params to my form params validation.

**Comment by jodosha** [comment]
@SleeplessByte We're in favor of clarity and explicitness. Please for now whitelist params from router too.

**Comment by SleeplessByte** [comment]
:+1: Fine with me, but this should be documented because it is only documented that using a router param will give access to it in params, when it clearly doesn't in this case :) @jodosha
